### ISSUE TITLE
Have you managed to include three-mesh-ui ?

### ISSUE THREAD

**Issue by felixmariotto** [SteveSmith16384/vr-sentinel#1]
Have you managed to include [three-mesh-ui](https://github.com/felixmariotto/three-mesh-ui) ?
If not, I'm willing to help.

**Comment by SteveSmith16384** [comment]
No.  Probably due to my lack of knowledge of the intricacies of Javascript, but I couldn't get the imports to work.  I'm going to leave it for now, but I'll let you know if I have another go.
